### ISSUE TITLE
include cancer hallmarks

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#106]
## Description
* [x] **WHY - What is the problem this feature would answer?**  

Showcase whether a specific target is involved in a major cancer pathway, either suppressing or promoting a cancer hallmark. 

* [ ] **HOW are we going to solve the problem?**  

This is the blocker so far. COSMIC does not have an API.

* [x] **WHAT would this look like?**

 ![](https://user-images.githubusercontent.com/112610/30536033-3cd0606a-9c5c-11e7-8f32-f25aa78a746b.png)

### Get to a prototype at branch.targetvalidation.org:
> Write code + **tests** + docs. Isolate the work in feature branches.  
> Use as many PRs as you need.  
> Write tests in the same or different PRs, as is convenient for you.  
> As each PR is merged, add a comment to this issue referencing the PRs.  

- [ ] Feature tag *Code should have a feature tag to be disabled by default.*
- [ ] Minimal functional testing
- [ ] Minimal docs
- [ ] if on webapp, test a deployment on netlify
       
### Push to staging
- [ ] merged code and pushed to staging.targetvalidation.org
  **PULL request should be reviewed by 1-2 people at least**
- [ ] at least 1 week internal testing?
- [ ] received some feedback/input from users (eg. pharma scientist)

### Released
- [ ] in the release notes?
- [ ] documentation updated?		
- [ ] blog post?
- [ ] users that requested it originally informed?

## Make sure you can measure impact
> As dev team we want to know if a new feature are succesful.
> To do that we need to define metrics to assess the impact of each new feature we introduce to the platform
- [ ] metric identified 
- [ ] identify the one metric that matters (OMTM)
