### ISSUE TITLE
"what's new" - highlight new evidence / facets by date of evidence

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#13]
## Description
* [x] **WHY - What is the problem this feature would answer?**  

Find out what's new for your target or T-D associations, with respect to the last time you visited the platform.

- facets on the evidence page which allows sorting by date of addition to the platform and highlighting of  new data since the last release.
- emails/push notification about new data on your disease (for eg.)

* [x] **WHO wants it**
GSK, Biogen VPs have requested the feature to help them track updates and keep up-to-date without having to visit the platform.

* [ ] **HOW are we going to solve the problem?**  

* [ ] **WHAT would this look like?**
> *Screenshots and mock-ups are great*

**Comment by ElaineMcA** [comment]
Requires user profile/ login.
