### ISSUE TITLE
Remove literature injection step from the data pipeline

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#143]
## Description
* [x] **WHY - What is the problem this feature would answer?**  

See the document: https://docs.google.com/document/d/1eo2YXJCEdvbckjOqUo9fnmkZOBKtQEsq8MivhF7oU8k/edit

Briefly, 
Currently we call the api.opentargets.io API to get abstracts in the evidence page:

https://api.opentargets.io/v3/platform/public/evidence/filter?target=ENSG00000157764&disease=EFO_0000701&datasource=europepmc&size=10&from=0&sort=literature.date&search=&draw=1&expandefo=true

![image](https://user-images.githubusercontent.com/112610/40110034-e4f76d9a-58f6-11e8-8f8f-d93e7871240c.png)

This is very fast but requires the backend to keep up the literature pipeline. Albeit slower, it makes more engineering sense to outsource that to a _literature_ API. 

We would like to phase out abstracts from the data pipeline and the API.

* [x] **HOW are we going to solve the problem?**  

see document above.

If querying an external API becomes too slow, we can ask europePMC to add abstract to their evidence.

* [ ] **WHAT would this look like?**
