### ISSUE TITLE
Baseline Protein and RNA expression views

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#44]
_note this is a copy of #5, but no more as a PR._

## Description
**What is the problem this feature would answer?**  
A new summary view in the Protein and RNA expression views in Target Profile, which allows lab scientist to see where is the target expressed in healthy (normal) tissues and whether the target is more expressed in some healthy tissues than in others or homogeneously throughout the body. This allows to judge the specificity and pleiotropy of a potential target. 

### Design & Prototyping
**How are we going to solve the problem?**  

from @nikiforosk :1st_place_medal: 

This is the most recent mockup:
https://drive.google.com/file/d/0B2ocPmrjJs1gbkxzTG9DS0NMeEk/view?usp=sharing

Documentation about expression in this folder:
https://drive.google.com/drive/folders/0B2ocPmrjJs1gMVM3cGJFQXRuM0E?usp=sharing

@nikiforosk made a repository of the sites that he has looked at for expression graphs https://drive.google.com/open?id=0B2ocPmrjJs1gVmNNQWx1V0lrOW8

and a spreadsheet with a quick description and links https://docs.google.com/spreadsheets/d/1w0q4v2qXO4go5RIt-xy9Oj5J3vWoN0rBzoV0c4BlD2Y/edit?usp=sharing

Notes from our internal UX meeting live at https://docs.google.com/document/d/1ikw2xhXmqutyqw8wpVc3LFUJqjM-19SaKtSis9xQOFM/edit#

## Progress Tracker
- [x] Description complete
- [x] Proposal drafted 

### Get to a prototype at branch.targetvalidation.org:
Write code + **tests** + docs. Isolate the work in feature branches. 
Use as many PRs as you need.  
Write tests in the same or different PRs, as is convenient for you. 
As each PR is merged, add a comment to this issue referencing the PRs.  

- [x] netlify deployment
       
### Push to Beta
- [ ] merge code from branch above to master. Make sure tests are passing and master is not breaking. (We are working on automate this as much as possible, but we are admittedly not quite there).
  **PULL request should be reviewed by 1-2 people at least**
- [x] at least 1 week internal testing?
- [x] received some feedback/input from users (eg. pharma scientist)

### After Release
- [ ] in the release notes?
- [ ] documentation updated?		
- [ ] blog post?
- [ ] users that requested it originally informed?
