### ISSUE TITLE
thumbs up / thumbs down component for webapp features

### ISSUE THREAD

**Issue by emepyc** [opentargets/roadmap#77]
## Description
**What is the problem this feature would answer?**  
Long ago we agreed that it would be useful to have a UI element to allow users to vote-up and vote-down features in the webapp along with comments.

#### Design proposal
**How are we going to solve the problem?**  
Creating a new component that allows this feedback. We also need the backend infrastructure to collect this feedback 
 
#### Readme
**What does the solution look like?**  
WIP 

*** 

## Progress Tracker
- [ ] Description complete
- [ ] Proposal drafted 
- [ ] This feature's code will be checked into:  [webapp](https://github.com/opentargets/webapp), possibly rest_api, lambda? not sure how the backend should be developed
- [ ] README drafted *Paste here google doc link or link to markdown file, if not included as part of a PR already*

### Subtasks
*paste here the issue number of subtasks, if any*
 - [ ] agree on a UI design
 - [ ] decide and agree on the logic
 - [ ] decide how to collect the feedback
 - [ ] Implement both the UI and the backend

### Get to a prototype at branch.targetvalidation.org:
Write code + **tests** + docs. Isolate the work in feature branches.  
Use as many PRs as you need.  
Write tests in the same or different PRs, as is convenient for you.  
As each PR is merged, add a comment to this issue referencing the PRs.  

- [ ] Feature tag *Code should have a feature tag to be disabled by default.*
- [ ] branch name here: *branch*
- [ ] Minimal functional testing
- [ ] Minimal docs
- [ ] if on webapp, test a deployment on k8
       
### Push to Beta
- [ ] merge code from branch above to master. Make sure tests are passing and master is not breaking. (We are working on automate this as much as possible, but we are admittedly not quite there).
  **PULL request should be reviewed by 1-2 people at least**
- [ ] at least 1 week internal testing?
- [ ] received some feedback/input from users (eg. pharma scientist)

### Deploy
- [ ] in the release notes?
- [ ] documentation updated?		
- [ ] blog post?
- [ ] users that requested it originally informed?

## Make sure you can measure impact
As dev team we want to know if a new feature are succesful.
To do that we need to define metrics to assess the impact of each new feature we introduce to the platform
- [ ] metric identified 
- [ ] identify the one metric that matters (OMTM)
