### ISSUE TITLE
automated statistical comparison of rankings between data releases and competitors

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#8]
The main output of the platform is a ranking of genes, likely to be target for a given diseases.

There is currently no measurement of i) how stable is the ranking, ii) how succesful it might be on some surrogate measure (eg. retrospectively and iii) how it compares to competitors.

It would be good to have a measurement of the shift in the statistical distribution of rankings following a data release to quality check the output of our scoring model (ie. there should be some skew, but not an exagerated one)

Nice summary visualizations, like the one prototyped in https://github.com/opentargets/data_analytics
would be helpful.

Finally, just how different are our results from the rankings given by other platforms? Large discrepancies could help us zero in on bugs or potential improvements in our model.

- [ ] compare two data releases
- [ ] automate
- [ ] compare with at least one competitor (eg. disgenet)
- [ ] can we create a small "positive" control set of target <=> disease connections that we _should_ pick up?
