### ISSUE TITLE
automate mapping process to EFO

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#95]
## Description
* [x] **WHY - What is the problem this feature would answer?**  

Mapping diseases and phenotypes to our EFO ontology currently requires a lot of time. It would be great to have a package/piece of software/UI that helps automate and streamline the process. 

* [x] **HOW are we going to solve the problem?**  

The solution will likely leverage OBO files, OLS api and Zooma API
https://www.ebi.ac.uk/ols/docs/developer
https://www.ebi.ac.uk/spot/zooma/docs/api.html

* [ ] **WHAT would this look like?**
> *Screenshots and mock-ups are great*

**Comment by elipapa** [comment]
from Sira: 
> OpenTargets should first look at the preferred labels in EFO. When preferred_label is not available for a class, then use rdfs:label.

see #133
