### ISSUE TITLE
search by PMID

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#98]
## Description
* [x] **WHY - What is the problem this feature would answer?**  

Users wants to see the genes and disease involved by a single paper, or all the evidence that is associated with the same piece of literature.

* [ ] **HOW are we going to solve the problem?**  

Library API 

* [ ] **WHAT would this look like?**
> *Screenshots and mock-ups are great*
 

### Get to a prototype at branch.targetvalidation.org:
> Write code + **tests** + docs. Isolate the work in feature branches.  
> Use as many PRs as you need.  
> Write tests in the same or different PRs, as is convenient for you.  
> As each PR is merged, add a comment to this issue referencing the PRs.  

- [ ] Feature tag *Code should have a feature tag to be disabled by default.*
- [ ] Minimal functional testing
- [ ] Minimal docs
- [ ] if on webapp, test a deployment on netlify
       
### Push to staging
- [ ] merged code and pushed to staging.targetvalidation.org
  **PULL request should be reviewed by 1-2 people at least**
- [ ] at least 1 week internal testing?
- [ ] received some feedback/input from users (eg. pharma scientist)

### Released
- [ ] in the release notes?
- [ ] documentation updated?		
- [ ] blog post?
- [ ] users that requested it originally informed?

## Make sure you can measure impact
> As dev team we want to know if a new feature are succesful.
> To do that we need to define metrics to assess the impact of each new feature we introduce to the platform
- [ ] metric identified 
- [ ] identify the one metric that matters (OMTM)

**Comment by ElaineMcA** [comment]
As on 22Aug2018 checks:
can find PMID in library but no abstract.  
Search in LINK is very slow to load.

In OT, cannot search for PMID directly via search bar but in bibliography, abstract is presented with annotations as expected.

**Comment by ElaineMcA** [comment]
To be considered under pipeline refactor high level topic
